logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
    com:
      kv: debug

spring:
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      data-locations: classpath:init.sql
      mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
